spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  cloud:
    openfeign:
      okhttp:
        enabled: true

security:
  jwt:
    secret-key: hogihogihogihogihogihogihogihogihogihogiHOGIhogihogihogihogi
    expiration-time: 36000000000000
