spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  cloud:
    openfeign:
      client:
        config:
          PaymentClient:
            connect-timeout: 1000
            read-timeout: 10000
security:
  jwt:
    secret-key: hogihogihogihogihogihogihogihogihogihogiHOGIhogihogihogihogi
    expiration-time: 36000000000000
